"""
load_to_opdb.py
───────────────────────────────────────────────────────────────────────────────
One-time migration script.

Reads every CRM xlsx file found in RAW_DIR (same OP + DEVIS structure as the
existing DWH ETL) and loads the data into the MS SQL Server OperationalDB
using the op_db_v3 schema.

Tables populated, in dependency order:
    users  →  vehicles  →  clients  →  opportunities  →  quotes  →  sales

Usage
-----
    # 1. Install dependencies (once)
    pip install pandas openpyxl python-dotenv pyodbc

    # 2. Create a .env file (or export env vars) with the SQL Server creds:
    #    OPDB_HOST, OPDB_PORT, OPDB_NAME, OPDB_USER, OPDB_PASSWORD, OPDB_DRIVER

    # 3. Drop your xlsx files in  ./etl/raw/  (or override RAW_DIR)

    # 4. Run
    python load_to_opdb.py

Configuration
-------------
All config is read from environment variables (with safe defaults).
See the CONFIG block below.

ID strategy
-----------
    user_id    taken directly from source (Oppo_AssignedUserId / User_UserId)
    oppo_id    taken directly from source (Oppo_OpportunityId)
    quote_id   taken directly from source (Quot_OrderQuoteID)
    ar_ref     taken directly from source (AR_Ref)
    client_id  IDENTITY — auto-generated by SQL Server; no source equivalent
    sale_id    IDENTITY — auto-generated by SQL Server

deleted semantics (derived, not sourced from CRM)
    opportunities.deleted = 1  →  no quote was ever created for it
    opportunities.deleted = 0  →  at least one quote exists  ("won")
    quotes.deleted        = 1  →  quote did not lead to a sale
    quotes.deleted        = 0  →  quote led to a sale

Fake sales
----------
The source files contain no sales data.  To populate the sales table with
realistic-looking data, a random 10–23 % of newly inserted quotes are chosen
as "won" and a sale row is generated for each.  The matching quote row is
then flipped to deleted = 0, and so is its parent opportunity.
"""

# ── Standard library ──────────────────────────────────────────────────────────
import logging
import os
import random
import re
import shutil
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

# ── Third-party ───────────────────────────────────────────────────────────────
import pandas as pd
import pyodbc

# Add Backend directory to path for config import
BACKEND_DIR = Path(__file__).parent.parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from app.config import RAW_DIR_STR, PROCESSED_DIR_STR, REJECTED_DIR_STR, LOGS_DIR_STR
from app.config import OPDB_DRIVER, OPDB_SERVER, OPDB_PORT, OPDB_NAME, OPDB_USER, OPDB_PASSWORD

# =============================================================================
# CONFIG
# =============================================================================

# ── Directories ───────────────────────────────────────────────────────────────
RAW_DIR       = RAW_DIR_STR
PROCESSED_DIR = PROCESSED_DIR_STR
REJECTED_DIR  = REJECTED_DIR_STR
LOGS_DIR      = LOGS_DIR_STR

# ── Sheet names ───────────────────────────────────────────────────────────────
OP_SHEET    = "OP"
DEVIS_SHEET = "DEVIS"

# ── Fake-sales rate ───────────────────────────────────────────────────────────
FAKE_SALE_RATE_MIN = 0.10
FAKE_SALE_RATE_MAX = 0.23

# =============================================================================
# LOGGER
# =============================================================================

os.makedirs(LOGS_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(
            os.path.join(LOGS_DIR, f"opdb_load_{datetime.now().strftime('%Y%m%d')}.log")
        ),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("opdb_load")

# =============================================================================
# DATABASE
# =============================================================================

def get_connection() -> pyodbc.Connection:
    """
    Returns an open pyodbc connection to the OperationalDB.

    Supports both SQL Server auth (user + password) and Windows / trusted auth
    (leave OPDB_USER empty to fall through to Trusted_Connection=yes).
    """
    if OPDB_USER:
        conn_str = (
            f"DRIVER={{{OPDB_DRIVER}}};"
            f"SERVER={OPDB_HOST},{OPDB_PORT};"
            f"DATABASE={OPDB_NAME};"
            f"UID={OPDB_USER};"
            f"PWD={OPDB_PASSWORD};"
        )
    else:
        conn_str = (
            f"DRIVER={{{OPDB_DRIVER}}};"
            f"SERVER={OPDB_HOST},{OPDB_PORT};"
            f"DATABASE={OPDB_NAME};"
            "Trusted_Connection=yes;"
        )
    return pyodbc.connect(conn_str, autocommit=False)

# =============================================================================
# VEHICLE CATALOGUE
# =============================================================================
# ar_ref → (category, base_price)
# Used to populate the two columns that have no direct source equivalent.

_CATALOGUE: dict[str, tuple[str, float]] = {
    ar_ref: (category, float(price))
    for ar_ref, category, price in [
        ("SX11-GF+-080",    "SUV Compact", 105000),
        ("SX11-GS-080",     "SUV Compact",  98000),
        ("NL-3B-A10",       "SUV",         110000),
        ("NL-3B-B07",       "SUV",         110000),
        ("SX11-GF+-F36",    "SUV Compact", 105000),
        ("NL-3B-C19",       "SUV",         110000),
        ("NL-3B-E29",       "SUV",         110000),
        ("SX11-GF+-E32",    "SUV Compact", 105000),
        ("SX11-GS-D14",     "SUV Compact",  98000),
        ("NL-3B-D06",       "SUV",         110000),
        ("GX3-CVT-OR",      "Citadine",     70000),
        ("GX3-CVT-BAS",     "Citadine",     70000),
        ("GX3-CVT-WAA",     "Citadine",     70000),
        ("SX11-GS-E32",     "SUV Compact",  98000),
        ("LF7154B-208",     "Citadine",     75000),
        ("LF7154B-C23",     "Citadine",     75000),
        ("LF7154B-K22",     "Citadine",     75000),
        ("LF7154B-E43",     "Citadine",     75000),
        ("LF7154B-G65",     "Citadine",     75000),
        ("E22H-ADA",        "Electrique",  130000),
        ("SX11-GF+-D14",    "SUV Compact", 105000),
        ("SX11-GF+-G66",    "SUV Compact", 105000),
        ("SX11-GS-G66",     "SUV Compact",  98000),
        ("SS11-BVA",        "Berline",      85000),
        ("FX11",            "SUV",         140000),
        ("FY11",            "SUV",         135000),
        ("LP5SEF",          "Electrique",  125000),
        ("KX11",            "SUV",         150000),
        ("FY11-BA-ADE",     "SUV",         138000),
        ("GX3P-MT-WAA",     "Citadine",     72000),
        ("KX11-BA-LAK",     "SUV",         150000),
        ("SX11-MT-WAA",     "SUV Compact",  95000),
        ("GX3-CVT-BAS-CRM", "Citadine",     70000),
        ("GX3P-CVT-WAA",    "Citadine",     75000),
        ("KX11-BA-ACT",     "SUV",         150000),
        ("GE13-LAK",        "Electrique",  128000),
        ("FY11-BA-LAK",     "SUV",         138000),
        ("LF7154B-MT-208",  "Citadine",     72000),
        ("LF7154B-MT-C23",  "Citadine",     72000),
        ("LF7154B-MT-G65",  "Citadine",     72000),
        ("LF7154B-MT-E43",  "Citadine",     72000),
        ("GE13-BAS",        "Electrique",  128000),
        ("SS11-BVM",        "Berline",      80000),
        ("GE13-WAA",        "Electrique",  128000),
        ("SS11-MT-WAA",     "Berline",      80000),
        ("GX3-CVT-RAM",     "Citadine",     70000),
        ("LF7154B-MT-K22",  "Citadine",     72000),
        ("SX11-GS-F36",     "SUV Compact",  98000),
        ("SS11-MT-SAI",     "Berline",      80000),
        ("FY11-BA-WAA",     "SUV",         138000),
        ("EX5-EL-ADA",      "Electrique",  132000),
        ("EX5-EL-GRE",      "Electrique",  132000),
        ("EX5-EL-LAK",      "Electrique",  132000),
        ("EX5-EL-SAI",      "Electrique",  132000),
        ("EX5-EL-WAA",      "Electrique",  132000),
        ("SX11-GF-ADA",     "SUV Compact", 100000),
        ("SX11-GF-WAA",     "SUV Compact", 100000),
        ("SS11T-MT-ADA",    "Berline",      78000),
        ("SS11T-MT-BAS",    "Berline",      78000),
        ("SS11T-MT-SAI",    "Berline",      78000),
        ("SS11T-MT-WAA",    "Berline",      78000),
        ("SS11-AT-OR",      "Berline",      85000),
        ("SX11-GS-WAA",     "SUV Compact",  98000),
        ("SX11-GF-CS",      "SUV Compact", 102000),
        ("GX3-CVT-WAA-CRM", "Citadine",     70000),
        ("GX3-MT-BAS",      "Citadine",     68000),
        ("GX3-MT-WAA",      "Citadine",     68000),
        ("KX11-BA-WAA",     "SUV",         150000),
        ("SX11-CVT-WAA",    "SUV Compact",  98000),
        ("SS11-MT-ADA",     "Berline",      80000),
        ("SS11-MT-BAS",     "Berline",      80000),
        ("EX5",             "Electrique",  132000),
        ("SS11-AT-WAA",     "Berline",      85000),
        ("GC6M72M-WAA",     "Berline",      75000),
        ("GC6M72M-LAK",     "Berline",      75000),
        ("GC6M72M-RAM",     "Berline",      75000),
        ("GC6M72M-BAS",     "Berline",      75000),
        ("GC6M72M-SAI",     "Berline",      75000),
        ("GC6M72M-OR",      "Berline",      75000),
        ("FE-3JCM72-WAA",   "Berline",      68000),
        ("GX3-MT-RAM",      "Citadine",     68000),
        ("GX3-MT-OR",       "Citadine",     68000),
        ("GX3-MT-OR-CRM",   "Citadine",     68000),
        ("GX3-MT-WAA-CRM",  "Citadine",     68000),
        ("GX3-MT-RAM-CRM",  "Citadine",     68000),
        ("GX3-CVT-OR-CRM",  "Citadine",     70000),
        ("GX3-CVT-RAM-CRM", "Citadine",     70000),
        ("GX3-MT-BAS-CRM",  "Citadine",     68000),
        ("SX11",            "SUV Compact",  95000),
        ("SS11-AT-ADA",     "Berline",      85000),
        ("SS11-AT-SAI",     "Berline",      85000),
        ("SS11-AT-BAS",     "Berline",      85000),
        ("KX11-BA-SAF",     "SUV",         150000),
        ("GE13-SAF",        "Electrique",  128000),
        ("SX11-GS-SAF",     "SUV Compact",  98000),
        ("SX11-GF-RAM",     "SUV Compact", 100000),
        ("EX5EM-I-ADA",     "Electrique",  136000),
        ("NL-3B",           "SUV",         108000),
        ("SX11-DCT-WAA",    "SUV Compact",  98000),
        ("SX11-GS-ADA",     "SUV Compact",  98000),
        ("FE-7A74-BAS",     "Berline",      72000),
        ("SX11-GS-BAS",     "SUV Compact",  98000),
    ]
}

_DEFAULT_CATEGORY   = "Inconnu"
_DEFAULT_BASE_PRICE = None   # NULL — unknown variant; a wrong price is worse than NULL


def _catalogue_lookup(ar_ref: str) -> tuple[str, float | None]:
    entry = _CATALOGUE.get(ar_ref)
    if entry:
        return entry
    # Prefix match for unknown colour / trim variants of a known base model
    for key, val in _CATALOGUE.items():
        if ar_ref.startswith(key + "-") or key.startswith(ar_ref + "-"):
            return val
    return _DEFAULT_CATEGORY, _DEFAULT_BASE_PRICE


# =============================================================================
# SHARED HELPERS
# =============================================================================

def _safe_int(val) -> int | None:
    try:
        return int(val) if val is not None and not (
            isinstance(val, float) and pd.isna(val)
        ) else None
    except (ValueError, TypeError):
        return None


def _clean(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    s = str(val).strip()
    return s.title() if s else None


def _clean_lower(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    s = str(val).strip().lower()
    return s if s else None


def _clean_upper(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    s = str(val).strip().upper()
    return s if s else None


def _clean_raw(val) -> str | None:
    """Strip only — no case change (used for ar_ref, agency codes, etc.)."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    s = str(val).strip()
    return s if s else None


# =============================================================================
# XLSX LOADING
# =============================================================================

def _load_sheet(filepath: str, sheet_name: str) -> pd.DataFrame | None:
    """
    Load a single sheet from an xlsx file.
    Tries calamine first (fast, tolerant of corrupt stylesheets);
    falls back to openpyxl with a gradient-stop patch on failure.
    Returns a non-empty DataFrame or None.
    """
    try:
        xl = pd.ExcelFile(filepath, engine="calamine")
        if sheet_name not in xl.sheet_names:
            return None
        df = xl.parse(sheet_name)
        return df if not df.empty else None
    except ImportError:
        pass
    except Exception as exc:
        logger.warning(f"  calamine failed for '{sheet_name}': {exc} — trying openpyxl")

    # openpyxl fallback with duplicate-gradient-stop patch
    try:
        import openpyxl.styles.fills as _fills
        _orig = _fills._assign_position

        def _patched(stops):
            seen, result = {}, []
            for s in (stops or []):
                if s.position not in seen:
                    seen[s.position] = True
                    result.append(s)
            return result

        _fills._assign_position = _patched
        try:
            from openpyxl import load_workbook
            wb = load_workbook(filepath, read_only=True, data_only=True)
            if sheet_name not in wb.sheetnames:
                return None
            ws   = wb[sheet_name]
            rows = list(ws.iter_rows(values_only=True))
            wb.close()
        finally:
            _fills._assign_position = _orig

        if not rows:
            return None
        headers = [str(c) if c is not None else f"col_{i}" for i, c in enumerate(rows[0])]
        df = pd.DataFrame(rows[1:], columns=headers)
        return df if not df.empty else None

    except Exception as exc:
        logger.error(f"  Failed to load sheet '{sheet_name}': {exc}")
        return None


def _extract_agency_name(filepath: str) -> str:
    """'CRM AYDA-GABES_timestamp.xlsx' → 'Gabes'"""
    basename = re.sub(r"_\d{8}_\d{6}$", "", os.path.splitext(os.path.basename(filepath))[0])
    match    = re.search(r"-([^-]+)$", basename)
    return match.group(1).strip().title() if match else "Unknown"


# =============================================================================
# SCHEMA VALIDATION (minimal — rejects files missing critical columns)
# =============================================================================

_REQUIRED_OP = [
    "Oppo_OpportunityId", "Oppo_AssignedUserId",
    "Comp_Name", "Oppo_CreatedDate",
]
_REQUIRED_DEVIS = [
    "Quot_OrderQuoteID", "AR_Ref",
]


def _validate(df_op, df_devis, filename: str) -> dict:
    errors, warnings = [], []

    if df_op is None:
        errors.append("Sheet 'OP' is missing or empty")
    else:
        missing = [c for c in _REQUIRED_OP if c not in df_op.columns]
        if missing:
            errors.append(f"OP missing required columns: {missing}")

    if df_devis is None:
        errors.append("Sheet 'DEVIS' is missing or empty")
    else:
        missing = [c for c in _REQUIRED_DEVIS if c not in df_devis.columns]
        if missing:
            errors.append(f"DEVIS missing required columns: {missing}")
        if "User_UserId" not in (df_devis.columns if df_devis is not None else []):
            warnings.append("DEVIS missing 'User_UserId' — user fallback (name lookup) will be used for quotes")

    return {"valid": len(errors) == 0, "errors": errors, "warnings": warnings}


# =============================================================================
# PARSERS
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# USERS
# ─────────────────────────────────────────────────────────────────────────────

def load_users(df_op: pd.DataFrame, df_devis: pd.DataFrame) -> dict:
    """
    Extracts unique commercials from OP + DEVIS and inserts them into [users].
    Skips rows whose user_id already exists (no UPDATE — one-time load).

    Source → target:
        OP.Oppo_AssignedUserId  → users.user_id
        OP.User_LastName        → users.last_name
        OP.User_FirstName       → users.first_name
        OP.User_EmailAddress    → users.email
        OP.Chan_Description     → users.agency_name
        (hardcoded)             → users.role = 'Commercial'
    """
    report = {"total": 0, "inserted": 0, "skipped": 0, "errors": 0}
    users: dict[int, dict] = {}

    for _, row in df_op.iterrows():
        uid = _safe_int(row.get("Oppo_AssignedUserId"))
        if uid is None or uid in users:
            continue
        users[uid] = {
            "user_id":    uid,
            "last_name":  _clean(row.get("User_LastName")),
            "first_name": _clean(row.get("User_FirstName")),
            "email":      _clean_lower(row.get("User_EmailAddress")),
            "agency_name": _clean(row.get("Chan_Description")),
        }

    has_uid_col = "User_UserId" in df_devis.columns
    if not has_uid_col:
        logger.warning("DEVIS missing 'User_UserId' — no new users sourced from DEVIS.")
    else:
        for _, row in df_devis.iterrows():
            uid = _safe_int(row.get("User_UserId"))
            if uid is None or uid in users:
                continue
            users[uid] = {
                "user_id":    uid,
                "last_name":  _clean(row.get("User_LastName")),
                "first_name": _clean(row.get("User_FirstName")),
                "email":      None,   # DEVIS has no email column
                "agency_name": None,
            }

    report["total"] = len(users)
    if not users:
        logger.warning("No user data found — skipping users.")
        return report

    conn = get_connection()
    cur  = conn.cursor()
    try:
        for u in users.values():
            cur.execute("SELECT 1 FROM users WHERE user_id = ?", (u["user_id"],))
            if cur.fetchone():
                report["skipped"] += 1
                continue

            cur.execute(
                """
                INSERT INTO users (user_id, last_name, first_name, email, role, agency_name)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (u["user_id"], u["last_name"], u["first_name"],
                 u["email"], "Commercial", u["agency_name"]),
            )
            report["inserted"] += 1

        conn.commit()
        logger.info(f"Users — inserted: {report['inserted']}, skipped: {report['skipped']}")
    except Exception as exc:
        conn.rollback()
        logger.error(f"Error loading users: {exc}")
        report["errors"] += 1
        raise
    finally:
        cur.close()
        conn.close()

    return report


def _resolve_user_id_by_name(cur, last_name: str, first_name: str) -> int | None:
    """Fallback user resolution when User_UserId is absent from DEVIS."""
    if not last_name or not first_name:
        return None
    cur.execute(
        """
        SELECT TOP 1 user_id FROM users
        WHERE UPPER(last_name)  = UPPER(?)
          AND UPPER(first_name) = UPPER(?)
        """,
        (last_name, first_name),
    )
    row = cur.fetchone()
    return row[0] if row else None


# ─────────────────────────────────────────────────────────────────────────────
# VEHICLES
# ─────────────────────────────────────────────────────────────────────────────

def load_vehicles(df_devis: pd.DataFrame) -> dict:
    """
    Extracts unique vehicles from DEVIS and inserts them into [vehicles].

    Source → target:
        DEVIS.AR_Ref    → vehicles.ar_ref      (PK)
        DEVIS.AR_Design → vehicles.ar_design
        DEVIS.Marque    → vehicles.brand
        DEVIS.Modèle    → vehicles.model
        catalogue       → vehicles.category
        catalogue       → vehicles.base_price
    """
    report = {"total": 0, "inserted": 0, "skipped": 0, "errors": 0}

    if "AR_Ref" not in df_devis.columns:
        logger.warning("DEVIS missing 'AR_Ref' — skipping vehicles.")
        return report

    keep = [c for c in ("AR_Ref", "AR_Design", "Marque", "Modèle") if c in df_devis.columns]
    vehicles_df = (
        df_devis[keep]
        .dropna(subset=["AR_Ref"])
        .drop_duplicates(subset=["AR_Ref"])
    )
    report["total"] = len(vehicles_df)

    conn = get_connection()
    cur  = conn.cursor()
    try:
        for _, row in vehicles_df.iterrows():
            ar_ref = _clean_raw(row["AR_Ref"])
            if not ar_ref:
                report["skipped"] += 1
                continue

            cur.execute("SELECT 1 FROM vehicles WHERE ar_ref = ?", (ar_ref,))
            if cur.fetchone():
                report["skipped"] += 1
                continue

            ar_design          = _clean(row.get("AR_Design"))
            brand              = _clean(row.get("Marque"))
            model              = _clean(row.get("Modèle"))
            category, base_price = _catalogue_lookup(ar_ref)

            cur.execute(
                """
                INSERT INTO vehicles (ar_ref, ar_design, brand, model, category, base_price)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (ar_ref, ar_design, brand, model, category, base_price),
            )
            report["inserted"] += 1

        conn.commit()
        logger.info(
            f"Vehicles — inserted: {report['inserted']}, skipped: {report['skipped']}"
        )
    except Exception as exc:
        conn.rollback()
        logger.error(f"Error loading vehicles: {exc}")
        report["errors"] += 1
        raise
    finally:
        cur.close()
        conn.close()

    return report


# ─────────────────────────────────────────────────────────────────────────────
# CLIENTS  (called inline from load_opportunities via the caller's cursor)
# ─────────────────────────────────────────────────────────────────────────────

def _get_or_create_client(cur, full_name, email, city) -> int | None:
    """
    Look up or INSERT a client row using the caller's cursor (participates in
    the same transaction as the opportunity INSERT).

    Dedup key: (UPPER(full_name), LOWER(email))
    Falls back to name-only lookup when email is NULL.

    Returns client_id (generated by IDENTITY) or None if full_name is blank.
    """
    name_clean  = _clean_upper(full_name)
    email_clean = _clean_lower(email)
    city_clean  = _clean(city)

    if not name_clean:
        return None

    if email_clean:
        cur.execute(
            """
            SELECT TOP 1 client_id FROM clients
            WHERE UPPER(TRIM(full_name)) = ?
              AND LOWER(TRIM(email))     = ?
            """,
            (name_clean, email_clean),
        )
    else:
        cur.execute(
            """
            SELECT TOP 1 client_id FROM clients
            WHERE UPPER(TRIM(full_name)) = ?
              AND email IS NULL
            """,
            (name_clean,),
        )
    row = cur.fetchone()
    if row:
        return row[0]

    # INSERT — client_id is IDENTITY; retrieve it via OUTPUT INSERTED
    cur.execute(
        """
        INSERT INTO clients (full_name, email, city)
        OUTPUT INSERTED.client_id
        VALUES (?, ?, ?)
        """,
        (name_clean.title(), email_clean, city_clean),
    )
    new_row = cur.fetchone()
    client_id = new_row[0] if new_row else None
    logger.debug(f"  New client inserted: '{name_clean}' (id={client_id})")
    return client_id


# ─────────────────────────────────────────────────────────────────────────────
# OPPORTUNITIES
# ─────────────────────────────────────────────────────────────────────────────

def load_opportunities(df_op: pd.DataFrame) -> dict:
    """
    Inserts opportunities from the OP sheet into [opportunities].

    All rows are inserted with deleted = 1 (no quote yet).
    After load_quotes() commits, mark_won_opportunities() flips deleted = 0
    on every opportunity that has at least one linked quote.

    Source → target:
        OP.Oppo_OpportunityId  → opportunities.oppo_id    (PK)
        OP.Oppo_AssignedUserId → opportunities.user_id    (FK)
        OP.Chan_Description    → opportunities.agency_name
        OP.Oppo_CreatedDate    → opportunities.created_date
        OP.comp_reference      → opportunities.client_reference
        OP.Comp_Name           → clients.full_name  (via _get_or_create_client)
        OP.Emai_EmailAddress   → clients.email
        OP.Addr_City           → clients.city
    """
    report = {"total": 0, "inserted": 0, "skipped": 0, "errors": 0}

    df = (
        df_op
        .dropna(subset=["Oppo_OpportunityId"])
        .drop_duplicates(subset=["Oppo_OpportunityId"])
        .copy()
    )
    df["Oppo_CreatedDate"] = pd.to_datetime(
        df["Oppo_CreatedDate"], dayfirst=True, errors="coerce"
    )
    report["total"] = len(df)

    conn = get_connection()
    cur  = conn.cursor()
    try:
        for _, row in df.iterrows():
            oppo_id = _safe_int(row["Oppo_OpportunityId"])
            if oppo_id is None:
                report["skipped"] += 1
                continue

            cur.execute("SELECT 1 FROM opportunities WHERE oppo_id = ?", (oppo_id,))
            if cur.fetchone():
                report["skipped"] += 1
                continue

            user_id = _safe_int(row.get("Oppo_AssignedUserId"))

            client_id = _get_or_create_client(
                cur,
                full_name=row.get("Comp_Name"),
                email=row.get("Emai_EmailAddress"),
                city=row.get("Addr_City"),
            )

            agency_name      = _clean(row.get("Chan_Description"))
            client_reference = _clean(row.get("comp_reference"))
            raw_date         = row.get("Oppo_CreatedDate")
            created_date     = (
                raw_date.to_pydatetime()
                if pd.notna(raw_date) and hasattr(raw_date, "to_pydatetime")
                else None
            )

            cur.execute(
                """
                INSERT INTO opportunities
                    (oppo_id, user_id, client_id, agency_name,
                     created_date, client_reference, deleted)
                VALUES (?, ?, ?, ?, ?, ?, 1)
                """,
                (oppo_id, user_id, client_id, agency_name,
                 created_date, client_reference),
            )
            report["inserted"] += 1

        conn.commit()
        logger.info(
            f"Opportunities — inserted: {report['inserted']}, "
            f"skipped: {report['skipped']}, errors: {report['errors']}"
        )
    except Exception as exc:
        conn.rollback()
        logger.error(f"Error loading opportunities: {exc}")
        report["errors"] += 1
        raise
    finally:
        cur.close()
        conn.close()

    return report


def mark_won_opportunities() -> int:
    """
    Flips deleted = 0 on opportunities that now have at least one linked quote.
    Called after load_quotes() commits so the new quote rows are visible.
    """
    conn = get_connection()
    cur  = conn.cursor()
    try:
        cur.execute(
            """
            UPDATE opportunities
            SET    deleted = 0
            WHERE  deleted = 1
              AND  oppo_id IN (
                  SELECT DISTINCT oppo_id
                  FROM   quotes
                  WHERE  oppo_id IS NOT NULL
              )
            """
        )
        updated = cur.rowcount
        conn.commit()
        if updated:
            logger.info(f"Opportunities marked won (deleted=0): {updated}")
        return updated
    except Exception as exc:
        conn.rollback()
        logger.error(f"Error in mark_won_opportunities: {exc}")
        raise
    finally:
        cur.close()
        conn.close()


# ─────────────────────────────────────────────────────────────────────────────
# QUOTES  +  FAKE SALES
# ─────────────────────────────────────────────────────────────────────────────

def load_quotes(df_devis: pd.DataFrame) -> dict:
    """
    Inserts quotes from DEVIS into [quotes], then generates fake sales for
    10–23 % of the newly inserted quotes.

    All quotes start with deleted = 1.  After fake sales are inserted the
    "won" quotes are flipped to deleted = 0 in the same transaction.
    Then mark_won_opportunities() propagates the win upward.

    Source → target:
        DEVIS.Quot_OrderQuoteID  → quotes.quote_id   (PK)
        DEVIS.Quot_opportunityid → quotes.oppo_id    (FK, nullable)
        DEVIS.AR_Ref             → quotes.ar_ref     (FK)
        DEVIS.User_UserId        → quotes.user_id    (preferred)
        DEVIS.User_LastName/FirstName → fallback name lookup
        DEVIS.Quot_CreatedDate   → quotes.created_date
        opportunities.agency_name → quotes.agency_name  (inherited)
        opportunities.client_id  → quotes.client_id     (inherited)
        vehicles.base_price      → quotes.price          (looked up)
    """
    report = {
        "total": 0, "inserted": 0, "skipped": 0, "errors": 0,
        "sales_generated": 0,
    }

    if "Quot_OrderQuoteID" not in df_devis.columns:
        logger.warning("DEVIS missing 'Quot_OrderQuoteID' — skipping quotes.")
        return report

    df = (
        df_devis
        .dropna(subset=["Quot_OrderQuoteID"])
        .drop_duplicates(subset=["Quot_OrderQuoteID"], keep="first")
        .copy()
    )
    if "Quot_CreatedDate" in df.columns:
        df["Quot_CreatedDate"] = pd.to_datetime(
            df["Quot_CreatedDate"], dayfirst=True, errors="coerce"
        )
    else:
        df["Quot_CreatedDate"] = pd.NaT

    report["total"]  = len(df)
    has_user_id_col  = "User_UserId" in df.columns

    if not has_user_id_col:
        logger.warning(
            "DEVIS missing 'User_UserId' — resolving quote users by name."
        )

    user_cache:    dict = {}
    vehicle_cache: dict = {}
    oppo_cache:    dict = {}

    conn = get_connection()
    cur  = conn.cursor()
    try:
        newly_inserted: list[dict] = []

        for _, row in df.iterrows():
            quote_id = _safe_int(row["Quot_OrderQuoteID"])
            if quote_id is None:
                report["skipped"] += 1
                continue

            cur.execute("SELECT 1 FROM quotes WHERE quote_id = ?", (quote_id,))
            if cur.fetchone():
                report["skipped"] += 1
                continue

            # ── ar_ref + price ────────────────────────────────────────────
            ar_ref = _clean_raw(row.get("AR_Ref"))
            if ar_ref and ar_ref not in vehicle_cache:
                cur.execute(
                    "SELECT base_price FROM vehicles WHERE ar_ref = ?", (ar_ref,)
                )
                r = cur.fetchone()
                vehicle_cache[ar_ref] = r[0] if r else None
            price = vehicle_cache.get(ar_ref) if ar_ref else None

            # ── oppo_id FK (validate it exists) ──────────────────────────
            oppo_id = _safe_int(row.get("Quot_opportunityid"))
            if oppo_id is not None:
                if oppo_id not in oppo_cache:
                    cur.execute(
                        "SELECT 1 FROM opportunities WHERE oppo_id = ?", (oppo_id,)
                    )
                    oppo_cache[oppo_id] = cur.fetchone() is not None
                if not oppo_cache[oppo_id]:
                    logger.warning(
                        f"  quote {quote_id}: oppo_id {oppo_id} not found — "
                        "inserting with oppo_id = NULL"
                    )
                    oppo_id = None

            # ── user_id ───────────────────────────────────────────────────
            user_id = _resolve_quote_user(
                row, has_user_id_col, cur, user_cache, quote_id
            )

            # ── agency_name + client_id from linked opportunity ───────────
            agency_name = None
            client_id   = None
            if oppo_id is not None:
                cur.execute(
                    "SELECT agency_name, client_id FROM opportunities WHERE oppo_id = ?",
                    (oppo_id,),
                )
                r = cur.fetchone()
                if r:
                    agency_name, client_id = r[0], r[1]

            # ── created_date ──────────────────────────────────────────────
            raw_date     = row.get("Quot_CreatedDate")
            created_date = (
                raw_date.to_pydatetime()
                if pd.notna(raw_date) and hasattr(raw_date, "to_pydatetime")
                else None
            )

            # ── Insert with deleted = 1 ───────────────────────────────────
            cur.execute(
                """
                INSERT INTO quotes
                    (quote_id, oppo_id, ar_ref, user_id, client_id,
                     agency_name, price, created_date, deleted)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)
                """,
                (quote_id, oppo_id, ar_ref, user_id, client_id,
                 agency_name, price, created_date),
            )
            report["inserted"] += 1
            newly_inserted.append({
                "quote_id":     quote_id,
                "oppo_id":      oppo_id,
                "ar_ref":       ar_ref,
                "user_id":      user_id,
                "client_id":    client_id,
                "agency_name":  agency_name,
                "price":        price,
                "created_date": created_date.date() if created_date else None,
            })

        # ── Fake sales ────────────────────────────────────────────────────
        won_quote_ids: list[int] = []

        if newly_inserted:
            rate   = random.uniform(FAKE_SALE_RATE_MIN, FAKE_SALE_RATE_MAX)
            k      = max(1, round(len(newly_inserted) * rate))
            chosen = random.sample(newly_inserted, min(k, len(newly_inserted)))
            today  = date.today()

            for q in chosen:
                sale_date = _random_date_after(q["created_date"], today)
                cur.execute(
                    """
                    INSERT INTO sales
                        (quote_id, oppo_id, user_id, client_id, ar_ref,
                         agency_name, sale_date, quantity, final_price)
                    SELECT ?, ?, ?, ?, ?, ?, ?, 1, ?
                    WHERE NOT EXISTS (
                        SELECT 1 FROM sales WHERE quote_id = ?
                    )
                    """,
                    (
                        q["quote_id"], q["oppo_id"], q["user_id"],
                        q["client_id"], q["ar_ref"],
                        q["agency_name"], sale_date, q["price"],
                        q["quote_id"],
                    ),
                )
                won_quote_ids.append(q["quote_id"])

            # Flip won quotes to deleted = 0
            if won_quote_ids:
                placeholders = ",".join("?" * len(won_quote_ids))
                cur.execute(
                    f"UPDATE quotes SET deleted = 0 WHERE quote_id IN ({placeholders})",
                    won_quote_ids,
                )
                logger.info(f"Quotes marked won (deleted=0): {len(won_quote_ids)}")

            report["sales_generated"] = len(chosen)
            pct = len(chosen) / len(newly_inserted) * 100
            logger.info(
                f"Fake sales generated: {len(chosen)} ({pct:.1f}% of new quotes)"
            )

        conn.commit()
        logger.info(
            f"Quotes — inserted: {report['inserted']}, "
            f"skipped: {report['skipped']}, errors: {report['errors']}"
        )

    except Exception as exc:
        conn.rollback()
        logger.error(f"Error loading quotes: {exc}")
        report["errors"] += 1
        raise
    finally:
        cur.close()
        conn.close()

    # Propagate wins to opportunities (needs its own connection after commit)
    if report["inserted"] > 0:
        mark_won_opportunities()

    return report


def _resolve_quote_user(row, has_user_id_col: bool, cur, cache: dict, quote_id: int):
    if has_user_id_col:
        uid       = _safe_int(row.get("User_UserId"))
        cache_key = ("id", uid)
        if cache_key not in cache:
            if uid is None:
                cache[cache_key] = None
            else:
                cur.execute("SELECT 1 FROM users WHERE user_id = ?", (uid,))
                cache[cache_key] = uid if cur.fetchone() else None
                if cache[cache_key] is None:
                    logger.warning(
                        f"  quote {quote_id}: user_id {uid} not found in users"
                    )
        return cache[cache_key]
    else:
        ln  = _clean(row.get("User_LastName"))
        fn  = _clean(row.get("User_FirstName"))
        cache_key = ("name", ln, fn)
        if cache_key not in cache:
            cache[cache_key] = _resolve_user_id_by_name(cur, ln, fn)
            if cache[cache_key] is None:
                logger.warning(
                    f"  quote {quote_id}: user '{fn} {ln}' not found in users"
                )
        return cache[cache_key]


def _random_date_after(start: date | None, end: date) -> date:
    if start is None or start >= end:
        return end
    delta = (end - start).days
    return start + timedelta(days=random.randint(1, delta))


# =============================================================================
# FILE PROCESSING
# =============================================================================

def _move_file(filepath: str, dest_dir: str) -> str:
    os.makedirs(dest_dir, exist_ok=True)
    basename  = re.sub(r"_\d{8}_\d{6}$", "", os.path.splitext(os.path.basename(filepath))[0])
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dest_path = os.path.join(dest_dir, f"{basename}_{timestamp}.xlsx")
    shutil.move(filepath, dest_path)
    return os.path.basename(dest_path)


def process_file(filepath: str) -> dict:
    filename = os.path.basename(filepath)
    logger.info(f"=== Processing: {filename} ===")

    report = {
        "file":          filename,
        "agency":        None,
        "validation":    {"errors": [], "warnings": []},
        "users":         {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "vehicles":      {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "clients":       {"inserted": 0},
        "opportunities": {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "quotes":        {"total": 0, "inserted": 0, "skipped": 0, "errors": 0,
                          "sales_generated": 0},
        "status":        "success",
        "error":         None,
    }

    if not os.path.exists(filepath):
        report["status"] = "failed"
        report["error"]  = f"File not found: {filepath}"
        logger.error(report["error"])
        return report

    try:
        df_op    = _load_sheet(filepath, OP_SHEET)
        df_devis = _load_sheet(filepath, DEVIS_SHEET)

        logger.info(f"  OP rows:    {len(df_op)    if df_op    is not None else 'MISSING'}")
        logger.info(f"  DEVIS rows: {len(df_devis) if df_devis is not None else 'MISSING'}")

        validation = _validate(df_op, df_devis, filename)
        report["validation"] = {
            "errors":   validation["errors"],
            "warnings": validation["warnings"],
        }
        for w in validation["warnings"]:
            logger.warning(f"  [WARN] {w}")

        if not validation["valid"]:
            for e in validation["errors"]:
                logger.error(f"  [REJECT] {e}")
            report["status"] = "rejected"
            report["error"]  = " | ".join(validation["errors"])
            _move_file(filepath, REJECTED_DIR)
            return report

        report["agency"] = _extract_agency_name(filepath)
        logger.info(f"  Agency: {report['agency']}")

        # ── Load order: dims before facts ─────────────────────────────────
        report["users"]         = load_users(df_op, df_devis)
        report["vehicles"]      = load_vehicles(df_devis)
        report["opportunities"] = load_opportunities(df_op)   # also loads clients inline
        report["quotes"]        = load_quotes(df_devis)       # also generates sales

        logger.info(f"=== Done: {filename} ===")

    except Exception as exc:
        report["status"] = "failed"
        report["error"]  = str(exc)
        logger.error(f"Pipeline failed for {filename}: {exc}", exc_info=True)

    dest  = PROCESSED_DIR if report["status"] == "success" else REJECTED_DIR
    moved = _move_file(filepath, dest)
    label = "processed" if dest == PROCESSED_DIR else "rejected"
    logger.info(f"Moved to {label}/: {moved}")
    return report


def process_all() -> list[dict]:
    files = [
        os.path.join(RAW_DIR, f)
        for f in os.listdir(RAW_DIR)
        if f.endswith(".xlsx") and not f.startswith("~$")
    ]
    logger.info(f"Found {len(files)} file(s) in {RAW_DIR}")
    if not files:
        logger.warning("Nothing to process. Drop xlsx files into etl/raw/ and re-run.")
        return []
    return [process_file(fp) for fp in sorted(files)]


# =============================================================================
# SUMMARY PRINTER
# =============================================================================

def _print_summary(reports: list[dict]) -> None:
    print("\n" + "=" * 60)
    print("LOAD SUMMARY")
    print("=" * 60)
    for r in reports:
        status = r["status"].upper()
        print(f"\n  [{status}] {r['file']}  (agency: {r['agency']})")
        if r["status"] != "success":
            print(f"    Error: {r['error']}")
            continue
        u = r["users"]
        v = r["vehicles"]
        o = r["opportunities"]
        q = r["quotes"]
        print(f"    Users         inserted={u['inserted']}  skipped={u['skipped']}")
        print(f"    Vehicles      inserted={v['inserted']}  skipped={v['skipped']}")
        print(f"    Opportunities inserted={o['inserted']}  skipped={o['skipped']}")
        print(f"    Quotes        inserted={q['inserted']}  skipped={q['skipped']}")
        print(f"    Sales (fake)  generated={q['sales_generated']}")
    print("\n" + "=" * 60)


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    logger.info("Starting OperationalDB load")
    logger.info(f"Target server: {OPDB_HOST}:{OPDB_PORT}  db={OPDB_NAME}")

    reports = process_all()
    _print_summary(reports)

    failed = [r for r in reports if r["status"] != "success"]
    if failed:
        logger.warning(f"{len(failed)} file(s) failed or were rejected.")
    else:
        logger.info("All files processed successfully.")
