# etl/pipeline/file_processor.py
"""
Main ETL entry point for a single xlsx file.

Flow:
  1. Load OP + DEVIS sheets (calamine engine preferred; openpyxl fallback)
  2. Schema validation  → reject immediately if required columns missing
  3. Parse users        → dim_user
  4. Parse vehicles     → dim_vehicle
  5. Parse opportunities → fact_opportunities  (calls get_or_create_client internally)
  6. Parse quotes       → fact_quotes  + fake sales → fact_sales
  7. Move file to processed/ or rejected/

ID strategy summary:
  - user_id  : taken directly from source (Oppo_AssignedUserId / User_UserId)
  - oppo_id  : taken directly from source (Oppo_OpportunityId / Quot_opportunityid)
  - quote_id : taken directly from source (Quot_OrderQuoteID)
  - ar_ref   : taken directly from source (AR_Ref)
  - client_id: SERIAL — auto-generated by PostgreSQL; no source equivalent
  - sale_id  : SERIAL — auto-generated by PostgreSQL
"""
import os
import re
import shutil
import pandas as pd
from datetime import datetime

from etl.pipeline.validators.schema_validator import validate_sheets
from etl.pipeline.parsers.parse_users         import parse_and_load_users
from etl.pipeline.parsers.parse_vehicles      import parse_and_load_vehicles
from etl.pipeline.parsers.parse_opportunities import parse_and_load_opportunities
from etl.pipeline.parsers.parse_quotes        import parse_and_load_quotes
from etl.utils.logger import logger
from dotenv import load_dotenv

load_dotenv()
BASE_DIR      = os.getenv("BASE_DIR", ".")
RAW_DIR       = os.path.join(BASE_DIR, "etl", "raw")
PROCESSED_DIR = os.path.join(BASE_DIR, "etl", "processed")
REJECTED_DIR  = os.path.join(BASE_DIR, "etl", "rejected")

OP_SHEET    = "OP"
DEVIS_SHEET = "DEVIS"


def _load_sheet(filepath: str, sheet_name: str):
    """
    Load a sheet from an xlsx file.
    Tries calamine first (faster, tolerates corrupt stylesheets);
    falls back to openpyxl with stylesheet patch on failure.
    Returns a DataFrame or None if the sheet is absent/empty.
    """
    try:
        xl = pd.ExcelFile(filepath, engine="calamine")
        if sheet_name not in xl.sheet_names:
            return None
        df = xl.parse(sheet_name)
        return df if not df.empty else None
    except ImportError:
        pass  # calamine not installed — fall through to openpyxl
    except Exception as e:
        logger.warning(f"  calamine failed for '{sheet_name}': {e} — trying openpyxl")

    # ── openpyxl fallback with duplicate-gradient-stop patch ────────────────
    try:
        import openpyxl.styles.fills as _fills
        _orig = _fills._assign_position

        def _patched(stops):
            seen, result = {}, []
            for s in (stops or []):
                if s.position not in seen:
                    seen[s.position] = True
                    result.append(s)
            return result

        _fills._assign_position = _patched
        try:
            from openpyxl import load_workbook
            wb = load_workbook(filepath, read_only=True, data_only=True)
            if sheet_name not in wb.sheetnames:
                return None
            ws   = wb[sheet_name]
            rows = list(ws.iter_rows(values_only=True))
            wb.close()
        finally:
            _fills._assign_position = _orig   # always restore

        if not rows:
            return None
        headers = [str(c) if c is not None else f"col_{i}" for i, c in enumerate(rows[0])]
        df = pd.DataFrame(rows[1:], columns=headers)
        return df if not df.empty else None

    except Exception as e:
        logger.error(f"  Failed to load sheet '{sheet_name}': {e}")
        return None


def _extract_agency_name(filepath: str) -> str:
    """'CRM AYDA-GABES.xlsx' → 'Gabes'"""
    basename = os.path.basename(filepath).replace(".xlsx", "")
    match    = re.search(r"-(.+)$", basename)
    return match.group(1).strip().title() if match else "Unknown"


def _move_file(filepath: str, dest_dir: str) -> str:
    os.makedirs(dest_dir, exist_ok=True)
    basename  = os.path.splitext(os.path.basename(filepath))[0]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dest_path = os.path.join(dest_dir, f"{basename}_{timestamp}.xlsx")
    shutil.move(filepath, dest_path)
    return os.path.basename(dest_path)


def process_file(filepath: str) -> dict:
    filename = os.path.basename(filepath)
    logger.info(f"=== Processing file: {filename} ===")

    report = {
        "file":          filename,
        "agency":        None,
        "validation":    {"errors": [], "warnings": []},
        "users":         {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "vehicles":      {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "clients":       {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "opportunities": {"total": 0, "inserted": 0, "skipped": 0, "errors": 0},
        "quotes":        {"total": 0, "inserted": 0, "skipped": 0, "errors": 0,
                          "sales_generated": 0},
        "status":        "success",
        "error":         None,
    }

    if not os.path.isabs(filepath):
        filepath = os.path.join(BASE_DIR, filepath)

    if not os.path.exists(filepath):
        report["status"] = "failed"
        report["error"]  = f"File not found: {filepath}"
        logger.error(report["error"])
        return report

    try:
        # ── Load sheets ───────────────────────────────────────────────────
        df_op    = _load_sheet(filepath, OP_SHEET)
        df_devis = _load_sheet(filepath, DEVIS_SHEET)

        logger.info(f"  OP rows:    {len(df_op)    if df_op    is not None else 'MISSING'}")
        logger.info(f"  DEVIS rows: {len(df_devis) if df_devis is not None else 'MISSING'}")

        # ── Schema validation ─────────────────────────────────────────────
        validation = validate_sheets(df_op, df_devis, filename)
        report["validation"] = {
            "errors":   validation["errors"],
            "warnings": validation["warnings"],
        }
        for w in validation["warnings"]:
            logger.warning(f"  [WARN] {w}")

        if not validation["valid"]:
            for e in validation["errors"]:
                logger.error(f"  [REJECT] {e}")
            report["status"] = "rejected"
            report["error"]  = " | ".join(validation["errors"])
            _move_file(filepath, REJECTED_DIR)
            return report

        # ── Agency name (from filename, informational only) ───────────────
        agency_name    = _extract_agency_name(filepath)
        report["agency"] = agency_name
        logger.info(f"  Agency: {agency_name}")

        # ── Parsers (order matters: dims before facts) ────────────────────
        report["users"]         = parse_and_load_users(df_op, df_devis)
        report["vehicles"]      = parse_and_load_vehicles(df_devis)
        report["opportunities"] = parse_and_load_opportunities(df_op)
        report["quotes"]        = parse_and_load_quotes(df_devis)

        logger.info(f"=== Done: {filename} ===")

    except Exception as e:
        report["status"] = "failed"
        report["error"]  = str(e)
        logger.error(f"Pipeline failed for {filename}: {e}", exc_info=True)

    dest = PROCESSED_DIR if report["status"] == "success" else REJECTED_DIR
    moved = _move_file(filepath, dest)
    label = "processed" if dest == PROCESSED_DIR else "rejected"
    logger.info(f"Moved to {label}/: {moved}")

    return report


def process_all_raw_files() -> list[dict]:
    files = [
        os.path.join(RAW_DIR, f)
        for f in os.listdir(RAW_DIR)
        if f.endswith(".xlsx") and not f.startswith("~$")
    ]
    logger.info(f"Found {len(files)} file(s) in raw/")
    return [process_file(fp) for fp in sorted(files)]
