# etl/pipeline/parsers/parse_quotes.py
"""
Loads quotes from the DEVIS sheet into fact_quotes.
Loads sales from the SALES sheet into fact_sales.

deleted semantics (DWH business rule — NOT a CRM source value):
  deleted=TRUE  → quote did not lead to a sale
  deleted=FALSE → quote led to a sale  ("won")

A quote is inserted with deleted=FALSE if its quote_id appears in the SALES
sheet (pre-generated by generate_fake_sales.py). All others get deleted=TRUE.
mark_won_opportunities() runs after commit to propagate wins upward.

Filtering rule:
  Only quotes whose Quot_opportunityid is non-NULL AND resolves to a row
  already present in fact_opportunities are inserted. All others are skipped.

ID strategy:
  - quote_id : direct from Quot_OrderQuoteID
  - oppo_id  : direct from Quot_opportunityid (FK, nullable)
  - user_id  : direct from User_UserId when present;
               fallback: (User_LastName, User_FirstName) → dim_user

Deduplication: if multiple rows share Quot_OrderQuoteID, only the FIRST is kept.

Column mapping (DEVIS → DWH):
  Quot_opportunityid → fact_quotes.oppo_id      (FK, nullable)
  Quot_OrderQuoteID  → fact_quotes.quote_id      (PK)
  AR_Ref             → fact_quotes.ar_ref        (FK → dim_vehicle)
  Quot_CreatedDate   → fact_quotes.created_date
  User_UserId        → fact_quotes.user_id       (preferred)
  User_LastName      → fallback name resolution
  User_FirstName     → fallback name resolution
  agency_name        → inherited from linked fact_opportunities row

Column mapping (SALES sheet → fact_sales):
  quote_id    → fact_sales.quote_id
  oppo_id     → fact_sales.oppo_id
  ar_ref      → fact_sales.ar_ref
  user_id     → fact_sales.user_id
  sale_date   → fact_sales.sale_date
  quantity    → fact_sales.quantity
  final_price → fact_sales.final_price
  client_id   → looked up from fact_opportunities.client_id
  agency_name → looked up from fact_opportunities.agency_name
"""
import pandas as pd

from etl.pipeline.parsers.parse_users import resolve_user_id_by_name
from etl.pipeline.parsers.parse_opportunities import mark_won_opportunities
from etl.utils.db import get_connection
from etl.utils.logger import logger


def parse_and_load_quotes(df_devis: pd.DataFrame, df_sales: pd.DataFrame | None = None) -> dict:
    report = {"total": 0, "inserted": 0, "skipped": 0, "errors": 0}

    if "Quot_OrderQuoteID" not in df_devis.columns:
        logger.warning("DEVIS missing 'Quot_OrderQuoteID' — skipping quotes.")
        return report

    # Build set of won quote_ids from the SALES sheet
    won_ids: set[int] = set()
    if df_sales is not None and not df_sales.empty and "quote_id" in df_sales.columns:
        for v in df_sales["quote_id"].dropna():
            qid = _safe_int(v)
            if qid is not None:
                won_ids.add(qid)
    logger.info(f"  SALES sheet: {len(won_ids)} won quote_id(s) found.")

    df = (
        df_devis
        .dropna(subset=["Quot_OrderQuoteID"])
        .drop_duplicates(subset=["Quot_OrderQuoteID"], keep="first")
        .copy()
    )
    if "Quot_CreatedDate" in df.columns:
        df["Quot_CreatedDate"] = pd.to_datetime(
            df["Quot_CreatedDate"], dayfirst=True, errors="coerce"
        )
    else:
        df["Quot_CreatedDate"] = pd.NaT

    report["total"] = len(df)
    has_user_id = "User_UserId" in df.columns
    if not has_user_id:
        logger.warning(
            "DEVIS missing 'User_UserId' — resolving quote users by "
            "(last_name, first_name)."
        )

    user_cache:    dict = {}
    vehicle_cache: dict = {}
    oppo_cache:    dict = {}

    conn = get_connection()
    cur  = conn.cursor()
    try:
        for _, row in df.iterrows():
            quote_id = _safe_int(row["Quot_OrderQuoteID"])
            if quote_id is None:
                report["skipped"] += 1
                continue

            cur.execute("SELECT 1 FROM fact_quotes WHERE quote_id = %s", (quote_id,))
            if cur.fetchone():
                report["skipped"] += 1
                continue

            # ── ar_ref + price ────────────────────────────────────────────
            ar_ref = _clean(row.get("AR_Ref"))
            if ar_ref and ar_ref not in vehicle_cache:
                cur.execute(
                    "SELECT base_price FROM dim_vehicle WHERE ar_ref = %s", (ar_ref,)
                )
                r = cur.fetchone()
                vehicle_cache[ar_ref] = r[0] if r else None
            price = vehicle_cache.get(ar_ref) if ar_ref else None

            # ── oppo_id FK ────────────────────────────────────────────────
            oppo_id = _safe_int(row.get("Quot_opportunityid"))
            if oppo_id is None:
                logger.debug(f"  quote {quote_id}: no oppo_id — skipping.")
                report["skipped"] += 1
                continue

            if oppo_id not in oppo_cache:
                cur.execute(
                    "SELECT 1 FROM fact_opportunities WHERE oppo_id = %s", (oppo_id,)
                )
                exists = cur.fetchone() is not None
                oppo_cache[oppo_id] = False if exists else None

            if oppo_cache[oppo_id] is None:
                logger.warning(
                    f"  quote {quote_id}: oppo_id {oppo_id} not found "
                    "in fact_opportunities — skipping."
                )
                report["skipped"] += 1
                continue

            if oppo_cache[oppo_id] is True:
                logger.debug(
                    f"  quote {quote_id}: oppo_id {oppo_id} already has a quote — skipping."
                )
                report["skipped"] += 1
                continue

            # ── user_id ───────────────────────────────────────────────────
            user_id = _resolve_user(row, has_user_id, cur, user_cache, quote_id)

            # ── agency_name from linked opportunity ───────────────────────
            agency_name = None
            cur.execute(
                "SELECT agency_name FROM fact_opportunities WHERE oppo_id = %s",
                (oppo_id,),
            )
            r = cur.fetchone()
            agency_name = r[0] if r else None

            # ── date ──────────────────────────────────────────────────────
            raw_date     = row.get("Quot_CreatedDate")
            created_date = (
                raw_date.date()
                if pd.notna(raw_date) and hasattr(raw_date, "date")
                else None
            )

            # ── deleted: FALSE if this quote appears in the SALES sheet ───
            is_won = quote_id in won_ids

            cur.execute(
                """
                INSERT INTO fact_quotes
                    (quote_id, oppo_id, ar_ref, user_id, client_id,
                     agency_name, price, created_date, deleted)
                VALUES (%s, %s, %s, %s,
                        (SELECT client_id FROM fact_opportunities
                         WHERE oppo_id = %s LIMIT 1),
                        %s, %s, %s, %s)
                """,
                (
                    quote_id, oppo_id, ar_ref, user_id,
                    oppo_id,
                    agency_name, price, created_date,
                    not is_won,
                ),
            )
            report["inserted"] += 1
            oppo_cache[oppo_id] = True

        conn.commit()
        logger.info(
            f"Quotes — inserted: {report['inserted']}, "
            f"skipped: {report['skipped']}, errors: {report['errors']}"
        )

    except Exception as e:
        conn.rollback()
        logger.error(f"Error loading quotes: {e}")
        report["errors"] += 1
        raise
    finally:
        cur.close()
        conn.close()

    # Runs after commit so new quote rows are visible to the UPDATE
    if report["inserted"] > 0:
        mark_won_opportunities()

    return report


# ── Helpers ───────────────────────────────────────────────────────────────────

def _resolve_user(row, has_user_id: bool, cur, cache: dict, quote_id: int):
    if has_user_id:
        uid       = _safe_int(row.get("User_UserId"))
        cache_key = ("id", uid)
        if cache_key not in cache:
            if uid is None:
                cache[cache_key] = None
            else:
                cur.execute("SELECT 1 FROM dim_user WHERE user_id = %s", (uid,))
                cache[cache_key] = uid if cur.fetchone() else None
                if cache[cache_key] is None:
                    logger.warning(
                        f"  quote {quote_id}: user_id {uid} not found in dim_user"
                    )
        return cache[cache_key]
    else:
        ln  = _clean(row.get("User_LastName"))
        fn  = _clean(row.get("User_FirstName"))
        cache_key = ("name", ln, fn)
        if cache_key not in cache:
            cache[cache_key] = resolve_user_id_by_name(cur, ln, fn, agency_name="")
            if cache[cache_key] is None:
                logger.warning(
                    f"  quote {quote_id}: user '{fn} {ln}' not found in dim_user"
                )
        return cache[cache_key]


def _safe_int(val):
    try:
        return int(val) if val is not None and not (
            isinstance(val, float) and pd.isna(val)
        ) else None
    except (ValueError, TypeError):
        return None


def _clean(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    return str(val).strip() or None
