# etl/pipeline/parsers/parse_clients.py
"""
Extracts clients from the OP sheet and upserts them into dim_client.

ID strategy:
  - client_id is SERIAL (auto-increment in PostgreSQL). There is NO client ID
    in the source files — a new ID is generated on every INSERT.

Deduplication key: (UPPER(TRIM(full_name)), LOWER(TRIM(email)))
  - If email is NULL, dedup falls back to name only.

get_or_create_client() uses the caller's cursor so it participates
in the same transaction as the opportunity insert.

Column mapping:
  Comp_Name           → dim_client.full_name
  Emai_EmailAddress   → dim_client.email
  Addr_City           → dim_client.city
"""
import pandas as pd
from etl.utils.logger import logger


def get_or_create_client(
    cur,
    full_name,
    email,
    city,
) -> int | None:
    """
    Look up or insert a client. Returns client_id (auto-generated) or None
    if full_name is empty.
    """
    name_clean  = _normalize_name(full_name)
    email_clean = _normalize_email(email)
    city_clean  = _normalize_city(city)

    if not name_clean:
        return None

    # ── Lookup ────────────────────────────────────────────────────────────────
    if email_clean:
        cur.execute(
            """
            SELECT client_id FROM dim_client
            WHERE UPPER(TRIM(full_name)) = %s
              AND LOWER(TRIM(email))     = %s
            LIMIT 1
            """,
            (name_clean, email_clean),
        )
    else:
        cur.execute(
            """
            SELECT client_id FROM dim_client
            WHERE UPPER(TRIM(full_name)) = %s
              AND email IS NULL
            LIMIT 1
            """,
            (name_clean,),
        )
    row = cur.fetchone()
    if row:
        return row[0]

    # ── Insert (client_id auto-generated by SERIAL) ───────────────────────────
    cur.execute(
        """
        INSERT INTO dim_client (full_name, email, city)
        VALUES (%s, %s, %s)
        RETURNING client_id
        """,
        (name_clean.title(), email_clean, city_clean),
    )
    client_id = cur.fetchone()[0]
    logger.debug(f"  New client inserted: '{name_clean}' (id={client_id})")
    return client_id


# ── Helpers ───────────────────────────────────────────────────────────────────
def _normalize_name(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    cleaned = str(val).strip().upper()
    return cleaned or None


def _normalize_email(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    cleaned = str(val).strip().lower()
    return cleaned or None


def _normalize_city(val) -> str | None:
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    cleaned = str(val).strip().title()
    return cleaned or None
